[package]
name = "lazy-config"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.9.8"
tokio.workspace = true
serde.workspace = true
color-eyre.workspace = true
lazy-core = { path = "../lazy-core/" }
